// 三阶段/w3_VueCLI/myapp/src/components/TodoList/TodoContent.vue
<template>
  <table class="table" ref="table">
    <thead>
      <tr>
        <th><input type="checkbox" v-model="checkAll" />全选</th>
        <th>#</th>
        <th>代办事项</th>
        <th>添加时间</th>
        <th>是否完成</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <!-- <tr
        is="todo-item"
        v-for="(item, idx) in list"
        :key="item.id"
        :item="item"
        :idx="idx"
      ></tr> -->
      <TodoItem
        v-for="(item, idx) in list"
        :key="item.id"
        :item="item"
        :idx="idx"
      />
    </tbody>
  </table>
</template>
<script>
import TodoItem from './TodoItem.vue'
export default {
  name:'TodoContent',
  props: {
    list: {
      type: Array,
      default() {
        return [];
      },
    },
  },
  computed: {
    checkAll: {
      get() {
        return this.list.every((item) => item.checked);
      },
      set(newVal) {
        this.list.forEach((item) => {
          item.checked = newVal;
        });
      },
    },
  },
  components: {
    TodoItem,
  },
};
</script>

// 三阶段/w5_React/src/components/Todolist/TodoContent.jsx
import React from 'react'

import TodoItem from './TodoItem'
import TodoStatus from './TodoStatus'


function TodoContent({todolist,selectAll}) {
    const checkAll = todolist.every(item => item.checked);

    return (
        <table className="table">
            <thead>
                <tr>
                    <th><input type="checkbox" checked={checkAll} onChange={selectAll} />全选</th>
                    <th>#</th>
                    <th>代办事项</th>
                    <th>添加时间</th>
                    <th>是否完成</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {
                    todolist.map((item, idx) => (
                        <TodoItem key={item.id} item={item} idx={idx} />
                    ))
                }

            </tbody>

            <tfoot>
                <TodoStatus todolist={todolist} />
            </tfoot>
        </table>
    )
}
export default TodoContent;
