// 三阶段/w3_VueCLI/myapp/src/components/TodoList/TodoItem.vue
<template>
  <tr :class="{ 'table-success': item.complete }" @click="selectItem(item.id)">
    <td>
        <!-- <input type="checkbox" v-model="item.checked" /> -->
        <input type="checkbox" :checked="item.checked" @click.stop="selectItem(item.id)" />
    </td>
    <td>{{ idx + 1 }}</td>
    <td>{{ item.todo }}</td>
    <td>{{item.addtime | formatDate('YYYY/MM/DD hh:mm:ss')}}</td>
    <td>{{ item.complete ? "是" : "否" }}</td>
    <td>
      <button
        type="button"
        class="btn btn-sm btn-outline-success"
        @click.stop="completeItem(item.id)"
      >
        完成
      </button>
      <button
        type="button"
        class="btn btn-sm btn-outline-danger"
        @click.stop="removeItem(item.id)"
      >
        删除
      </button>
    </td>
  </tr>
</template>
<script>
import Bus from './Bus';
import {formatDate} from '../../utils/filter';
export default {
  name: "TodoItem",
  props: {
    item: {
      type: Object,
      required: true,
    },
    idx: [Number, String],
  },
  methods: {
    completeItem(id) {
      Bus.$emit("complete", id);
    },
    removeItem(id) {
      Bus.$emit("remove", id);
    },
    selectItem(id) {
      Bus.$emit("select", id);
    },
  },
  filters:{
      formatDate
  }
};
</script>

// 三阶段/w5_React/src/components/Todolist/TodoItem.jsx
import React from 'react'
import myContext from './context'

function TodoItem({item,idx}){
    return (
        <myContext.Consumer>
            {
                (value)=>{
                    const {select,remove,complete} = value;
                    return <tr className={item.complete ? 'table-success':''} onClick={select.bind(null,item.id)}>
                        <td><input type="checkbox" checked={item.checked} readOnly /></td>
                        <td>{idx + 1}</td>
                        <td>{item.todo}</td>
                        <td>{item.addtime}</td>
                        <td>{item.complete ? '是' : '否'}</td>
                        <td>
                            <button type="button" className="btn btn-sm btn-outline-success" onClick={complete.bind(null,item.id)}>完成</button>
                            <button type="button" className="btn btn-sm btn-outline-danger" onClick={remove.bind(null,item.id)}>删除</button>
                        </td>
                    </tr>
                }
            }
        
        </myContext.Consumer>
    )
}
export default TodoItem;
