// 三阶段/w5_React/src/components/Todolist/TodoStatus.jsx
import React from 'react'

function TodoStatus({ todolist }) {
    const completeList = todolist.filter(item=>item.complete);
    const unCompleteList = todolist.filter(item=>!item.complete);
    return (
        <tr>
            <td colSpan="6">
                待办事项：{todolist.length}，完成：{completeList.length}，未完成：{unCompleteList.length}
            </td>
        </tr>
    )
}
export default TodoStatus;

// 三阶段/w3_VueCLI/myapp/src/components/TodoList/TodoStatus.vue
<template>
  <div>
    待办事项：{{ list.length }}，完成：{{ completeList.length }}，未完成：{{
      unCompleteList.length
    }}
  </div>
</template>
<script>
export default {
  name: "TodoStatus",
  props: {
    list: {
      type: Array,
      required: true,
    },
  },
  computed: {
    completeList() {
      return this.list.filter((item) => item.complete);
    },
    unCompleteList() {
      return this.list.filter((item) => !item.complete);
    },
  },
};
</script>
